// data-analysis-python\src\get_stocks_datalist_with_dates\get_stocks_datalist_with_dates.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0--rc3
// source: get_stocks_datalist_with_dates.proto

package get_stocks_datalist_with_dates

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetStocksDatalistWithDatesService_GetStocksDatalist_FullMethodName = "/GetStocksDatalistWithDatesService/GetStocksDatalist"
)

// GetStocksDatalistWithDatesServiceClient is the client API for GetStocksDatalistWithDatesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 株価情報を取得するためのサービスを定義
type GetStocksDatalistWithDatesServiceClient interface {
	GetStocksDatalist(ctx context.Context, in *GetStocksDatalistWithDatesRequest, opts ...grpc.CallOption) (*GetStocksDatalistWithDatesResponse, error)
}

type getStocksDatalistWithDatesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetStocksDatalistWithDatesServiceClient(cc grpc.ClientConnInterface) GetStocksDatalistWithDatesServiceClient {
	return &getStocksDatalistWithDatesServiceClient{cc}
}

func (c *getStocksDatalistWithDatesServiceClient) GetStocksDatalist(ctx context.Context, in *GetStocksDatalistWithDatesRequest, opts ...grpc.CallOption) (*GetStocksDatalistWithDatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStocksDatalistWithDatesResponse)
	err := c.cc.Invoke(ctx, GetStocksDatalistWithDatesService_GetStocksDatalist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetStocksDatalistWithDatesServiceServer is the server API for GetStocksDatalistWithDatesService service.
// All implementations must embed UnimplementedGetStocksDatalistWithDatesServiceServer
// for forward compatibility.
//
// 株価情報を取得するためのサービスを定義
type GetStocksDatalistWithDatesServiceServer interface {
	GetStocksDatalist(context.Context, *GetStocksDatalistWithDatesRequest) (*GetStocksDatalistWithDatesResponse, error)
	mustEmbedUnimplementedGetStocksDatalistWithDatesServiceServer()
}

// UnimplementedGetStocksDatalistWithDatesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetStocksDatalistWithDatesServiceServer struct{}

func (UnimplementedGetStocksDatalistWithDatesServiceServer) GetStocksDatalist(context.Context, *GetStocksDatalistWithDatesRequest) (*GetStocksDatalistWithDatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStocksDatalist not implemented")
}
func (UnimplementedGetStocksDatalistWithDatesServiceServer) mustEmbedUnimplementedGetStocksDatalistWithDatesServiceServer() {
}
func (UnimplementedGetStocksDatalistWithDatesServiceServer) testEmbeddedByValue() {}

// UnsafeGetStocksDatalistWithDatesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetStocksDatalistWithDatesServiceServer will
// result in compilation errors.
type UnsafeGetStocksDatalistWithDatesServiceServer interface {
	mustEmbedUnimplementedGetStocksDatalistWithDatesServiceServer()
}

func RegisterGetStocksDatalistWithDatesServiceServer(s grpc.ServiceRegistrar, srv GetStocksDatalistWithDatesServiceServer) {
	// If the following call pancis, it indicates UnimplementedGetStocksDatalistWithDatesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetStocksDatalistWithDatesService_ServiceDesc, srv)
}

func _GetStocksDatalistWithDatesService_GetStocksDatalist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStocksDatalistWithDatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetStocksDatalistWithDatesServiceServer).GetStocksDatalist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetStocksDatalistWithDatesService_GetStocksDatalist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetStocksDatalistWithDatesServiceServer).GetStocksDatalist(ctx, req.(*GetStocksDatalistWithDatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetStocksDatalistWithDatesService_ServiceDesc is the grpc.ServiceDesc for GetStocksDatalistWithDatesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetStocksDatalistWithDatesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GetStocksDatalistWithDatesService",
	HandlerType: (*GetStocksDatalistWithDatesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStocksDatalist",
			Handler:    _GetStocksDatalistWithDatesService_GetStocksDatalist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "get_stocks_datalist_with_dates.proto",
}
