// data-analysis-python\src\generate_chart_lc_sim\generate_chart_lc_sim.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0--rc2
// source: generate_chart_lc_sim.proto

package generate_chart_lc_sim

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GenerateChartLCService_GenerateChart_FullMethodName = "/GenerateChartLCService/GenerateChart"
)

// GenerateChartLCServiceClient is the client API for GenerateChartLCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GenerateChartLCServiceというサービスを定義
type GenerateChartLCServiceClient interface {
	GenerateChart(ctx context.Context, in *GenerateChartLCRequest, opts ...grpc.CallOption) (*GenerateChartLCResponse, error)
}

type generateChartLCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGenerateChartLCServiceClient(cc grpc.ClientConnInterface) GenerateChartLCServiceClient {
	return &generateChartLCServiceClient{cc}
}

func (c *generateChartLCServiceClient) GenerateChart(ctx context.Context, in *GenerateChartLCRequest, opts ...grpc.CallOption) (*GenerateChartLCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateChartLCResponse)
	err := c.cc.Invoke(ctx, GenerateChartLCService_GenerateChart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GenerateChartLCServiceServer is the server API for GenerateChartLCService service.
// All implementations must embed UnimplementedGenerateChartLCServiceServer
// for forward compatibility.
//
// GenerateChartLCServiceというサービスを定義
type GenerateChartLCServiceServer interface {
	GenerateChart(context.Context, *GenerateChartLCRequest) (*GenerateChartLCResponse, error)
	mustEmbedUnimplementedGenerateChartLCServiceServer()
}

// UnimplementedGenerateChartLCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGenerateChartLCServiceServer struct{}

func (UnimplementedGenerateChartLCServiceServer) GenerateChart(context.Context, *GenerateChartLCRequest) (*GenerateChartLCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateChart not implemented")
}
func (UnimplementedGenerateChartLCServiceServer) mustEmbedUnimplementedGenerateChartLCServiceServer() {
}
func (UnimplementedGenerateChartLCServiceServer) testEmbeddedByValue() {}

// UnsafeGenerateChartLCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GenerateChartLCServiceServer will
// result in compilation errors.
type UnsafeGenerateChartLCServiceServer interface {
	mustEmbedUnimplementedGenerateChartLCServiceServer()
}

func RegisterGenerateChartLCServiceServer(s grpc.ServiceRegistrar, srv GenerateChartLCServiceServer) {
	// If the following call pancis, it indicates UnimplementedGenerateChartLCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GenerateChartLCService_ServiceDesc, srv)
}

func _GenerateChartLCService_GenerateChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateChartLCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenerateChartLCServiceServer).GenerateChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GenerateChartLCService_GenerateChart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenerateChartLCServiceServer).GenerateChart(ctx, req.(*GenerateChartLCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GenerateChartLCService_ServiceDesc is the grpc.ServiceDesc for GenerateChartLCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GenerateChartLCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GenerateChartLCService",
	HandlerType: (*GenerateChartLCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateChart",
			Handler:    _GenerateChartLCService_GenerateChart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "generate_chart_lc_sim.proto",
}
