// get_stock_data.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0--rc2
// source: get_stock_data.proto

package ms_gateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetStockDataService_GetStockData_FullMethodName = "/GetStockDataService/GetStockData"
)

// GetStockDataServiceClient is the client API for GetStockDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GetStockServiceというサービスを定義
type GetStockDataServiceClient interface {
	GetStockData(ctx context.Context, in *GetStockDataRequest, opts ...grpc.CallOption) (*GetStockDataResponse, error)
}

type getStockDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetStockDataServiceClient(cc grpc.ClientConnInterface) GetStockDataServiceClient {
	return &getStockDataServiceClient{cc}
}

func (c *getStockDataServiceClient) GetStockData(ctx context.Context, in *GetStockDataRequest, opts ...grpc.CallOption) (*GetStockDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStockDataResponse)
	err := c.cc.Invoke(ctx, GetStockDataService_GetStockData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetStockDataServiceServer is the server API for GetStockDataService service.
// All implementations must embed UnimplementedGetStockDataServiceServer
// for forward compatibility.
//
// GetStockServiceというサービスを定義
type GetStockDataServiceServer interface {
	GetStockData(context.Context, *GetStockDataRequest) (*GetStockDataResponse, error)
	mustEmbedUnimplementedGetStockDataServiceServer()
}

// UnimplementedGetStockDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetStockDataServiceServer struct{}

func (UnimplementedGetStockDataServiceServer) GetStockData(context.Context, *GetStockDataRequest) (*GetStockDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStockData not implemented")
}
func (UnimplementedGetStockDataServiceServer) mustEmbedUnimplementedGetStockDataServiceServer() {}
func (UnimplementedGetStockDataServiceServer) testEmbeddedByValue()                             {}

// UnsafeGetStockDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetStockDataServiceServer will
// result in compilation errors.
type UnsafeGetStockDataServiceServer interface {
	mustEmbedUnimplementedGetStockDataServiceServer()
}

func RegisterGetStockDataServiceServer(s grpc.ServiceRegistrar, srv GetStockDataServiceServer) {
	// If the following call pancis, it indicates UnimplementedGetStockDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetStockDataService_ServiceDesc, srv)
}

func _GetStockDataService_GetStockData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetStockDataServiceServer).GetStockData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetStockDataService_GetStockData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetStockDataServiceServer).GetStockData(ctx, req.(*GetStockDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetStockDataService_ServiceDesc is the grpc.ServiceDesc for GetStockDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetStockDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GetStockDataService",
	HandlerType: (*GetStockDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStockData",
			Handler:    _GetStockDataService_GetStockData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "get_stock_data.proto",
}
