version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "8084:8080"
    environment:
      MYSQL_HOST: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
      MYSQL_DB: 
    depends_on:
      - mysql
    tty: true

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 
    ports:
      - "84:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
