# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: get_jp_tickers.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'get_jp_tickers.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14get_jp_tickers.proto\"\x15\n\x13GetJpTickersRequest\"\'\n\x14GetJpTickersResponse\x12\x0f\n\x07tickers\x18\x01 \x03(\t2R\n\x13GetJpTickersService\x12;\n\x0cGetJpTickers\x12\x14.GetJpTickersRequest\x1a\x15.GetJpTickersResponseB.Z,api-go/src/service/ms_gateway/get_jp_tickersb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_jp_tickers_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,api-go/src/service/ms_gateway/get_jp_tickers'
  _globals['_GETJPTICKERSREQUEST']._serialized_start=24
  _globals['_GETJPTICKERSREQUEST']._serialized_end=45
  _globals['_GETJPTICKERSRESPONSE']._serialized_start=47
  _globals['_GETJPTICKERSRESPONSE']._serialized_end=86
  _globals['_GETJPTICKERSSERVICE']._serialized_start=88
  _globals['_GETJPTICKERSSERVICE']._serialized_end=170
# @@protoc_insertion_point(module_scope)
