# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: get_stock_info_jq.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'get_stock_info_jq.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17get_stock_info_jq.proto\"(\n\x15GetStockInfoJqRequest\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\"4\n\x16GetStockInfoJqResponse\x12\x1a\n\x06stocks\x18\x01 \x03(\x0b\x32\n.StockInfo\"K\n\tStockInfo\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06sector\x18\x03 \x01(\t\x12\x10\n\x08industry\x18\x04 \x01(\t2Z\n\x15GetStockInfoJqService\x12\x41\n\x0eGetStockInfoJq\x12\x16.GetStockInfoJqRequest\x1a\x17.GetStockInfoJqResponseB1Z/api-go/src/service/ms_gateway/get_stock_info_jqb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_stock_info_jq_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/api-go/src/service/ms_gateway/get_stock_info_jq'
  _globals['_GETSTOCKINFOJQREQUEST']._serialized_start=27
  _globals['_GETSTOCKINFOJQREQUEST']._serialized_end=67
  _globals['_GETSTOCKINFOJQRESPONSE']._serialized_start=69
  _globals['_GETSTOCKINFOJQRESPONSE']._serialized_end=121
  _globals['_STOCKINFO']._serialized_start=123
  _globals['_STOCKINFO']._serialized_end=198
  _globals['_GETSTOCKINFOJQSERVICE']._serialized_start=200
  _globals['_GETSTOCKINFOJQSERVICE']._serialized_end=290
# @@protoc_insertion_point(module_scope)
