# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import get_stocks_datalist_with_dates_pb2 as get__stocks__datalist__with__dates__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in get_stocks_datalist_with_dates_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GetStocksDatalistWithDatesServiceStub(object):
    """株価情報を取得するためのサービスを定義
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStocksDatalist = channel.unary_unary(
                '/GetStocksDatalistWithDatesService/GetStocksDatalist',
                request_serializer=get__stocks__datalist__with__dates__pb2.GetStocksDatalistWithDatesRequest.SerializeToString,
                response_deserializer=get__stocks__datalist__with__dates__pb2.GetStocksDatalistWithDatesResponse.FromString,
                _registered_method=True)


class GetStocksDatalistWithDatesServiceServicer(object):
    """株価情報を取得するためのサービスを定義
    """

    def GetStocksDatalist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetStocksDatalistWithDatesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStocksDatalist': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStocksDatalist,
                    request_deserializer=get__stocks__datalist__with__dates__pb2.GetStocksDatalistWithDatesRequest.FromString,
                    response_serializer=get__stocks__datalist__with__dates__pb2.GetStocksDatalistWithDatesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GetStocksDatalistWithDatesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('GetStocksDatalistWithDatesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GetStocksDatalistWithDatesService(object):
    """株価情報を取得するためのサービスを定義
    """

    @staticmethod
    def GetStocksDatalist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GetStocksDatalistWithDatesService/GetStocksDatalist',
            get__stocks__datalist__with__dates__pb2.GetStocksDatalistWithDatesRequest.SerializeToString,
            get__stocks__datalist__with__dates__pb2.GetStocksDatalistWithDatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
