// data-analysis-python\src\get_stock_info_jq\get_stock_info_jq.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.29.0--rc2
// source: get_stock_info_jq.proto

package get_stock_info_jq

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// リクエストメッセージに国を指定するフィールドを追加
type GetStockInfoJqRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetStockInfoJqRequest) Reset() {
	*x = GetStockInfoJqRequest{}
	mi := &file_get_stock_info_jq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockInfoJqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockInfoJqRequest) ProtoMessage() {}

func (x *GetStockInfoJqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_get_stock_info_jq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockInfoJqRequest.ProtoReflect.Descriptor instead.
func (*GetStockInfoJqRequest) Descriptor() ([]byte, []int) {
	return file_get_stock_info_jq_proto_rawDescGZIP(), []int{0}
}

// 株式ティッカー情報を格納するレスポンスメッセージ
type GetStockInfoJqResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stocks []*StockInfo `protobuf:"bytes,1,rep,name=stocks,proto3" json:"stocks,omitempty"` // 株式情報のリスト
}

func (x *GetStockInfoJqResponse) Reset() {
	*x = GetStockInfoJqResponse{}
	mi := &file_get_stock_info_jq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockInfoJqResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockInfoJqResponse) ProtoMessage() {}

func (x *GetStockInfoJqResponse) ProtoReflect() protoreflect.Message {
	mi := &file_get_stock_info_jq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockInfoJqResponse.ProtoReflect.Descriptor instead.
func (*GetStockInfoJqResponse) Descriptor() ([]byte, []int) {
	return file_get_stock_info_jq_proto_rawDescGZIP(), []int{1}
}

func (x *GetStockInfoJqResponse) GetStocks() []*StockInfo {
	if x != nil {
		return x.Stocks
	}
	return nil
}

// 株式情報を表すメッセージ
type StockInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ticker   string `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`     // ティッカーシンボル
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`         // 銘柄名
	Sector   string `protobuf:"bytes,3,opt,name=sector,proto3" json:"sector,omitempty"`     // 業種
	Industry string `protobuf:"bytes,4,opt,name=industry,proto3" json:"industry,omitempty"` // 業界
	Date     string `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`         //
}

func (x *StockInfo) Reset() {
	*x = StockInfo{}
	mi := &file_get_stock_info_jq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockInfo) ProtoMessage() {}

func (x *StockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_get_stock_info_jq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockInfo.ProtoReflect.Descriptor instead.
func (*StockInfo) Descriptor() ([]byte, []int) {
	return file_get_stock_info_jq_proto_rawDescGZIP(), []int{2}
}

func (x *StockInfo) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *StockInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StockInfo) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *StockInfo) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *StockInfo) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

var File_get_stock_info_jq_proto protoreflect.FileDescriptor

var file_get_stock_info_jq_proto_rawDesc = []byte{
	0x0a, 0x17, 0x67, 0x65, 0x74, 0x5f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x5f, 0x6a, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x4a, 0x71, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x3c, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x49, 0x6e,
	0x66, 0x6f, 0x4a, 0x71, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x06,
	0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73,
	0x22, 0x7f, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x64, 0x75, 0x73, 0x74, 0x72, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x64, 0x75, 0x73, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x65, 0x32, 0x5a, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66,
	0x6f, 0x4a, 0x71, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x4a, 0x71, 0x12, 0x16, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x4a, 0x71, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x4a, 0x71, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x31, 0x5a,
	0x2f, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x6d, 0x73, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x67,
	0x65, 0x74, 0x5f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6a, 0x71,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_get_stock_info_jq_proto_rawDescOnce sync.Once
	file_get_stock_info_jq_proto_rawDescData = file_get_stock_info_jq_proto_rawDesc
)

func file_get_stock_info_jq_proto_rawDescGZIP() []byte {
	file_get_stock_info_jq_proto_rawDescOnce.Do(func() {
		file_get_stock_info_jq_proto_rawDescData = protoimpl.X.CompressGZIP(file_get_stock_info_jq_proto_rawDescData)
	})
	return file_get_stock_info_jq_proto_rawDescData
}

var file_get_stock_info_jq_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_get_stock_info_jq_proto_goTypes = []any{
	(*GetStockInfoJqRequest)(nil),  // 0: GetStockInfoJqRequest
	(*GetStockInfoJqResponse)(nil), // 1: GetStockInfoJqResponse
	(*StockInfo)(nil),              // 2: StockInfo
}
var file_get_stock_info_jq_proto_depIdxs = []int32{
	2, // 0: GetStockInfoJqResponse.stocks:type_name -> StockInfo
	0, // 1: GetStockInfoJqService.GetStockInfoJq:input_type -> GetStockInfoJqRequest
	1, // 2: GetStockInfoJqService.GetStockInfoJq:output_type -> GetStockInfoJqResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_get_stock_info_jq_proto_init() }
func file_get_stock_info_jq_proto_init() {
	if File_get_stock_info_jq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_get_stock_info_jq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_get_stock_info_jq_proto_goTypes,
		DependencyIndexes: file_get_stock_info_jq_proto_depIdxs,
		MessageInfos:      file_get_stock_info_jq_proto_msgTypes,
	}.Build()
	File_get_stock_info_jq_proto = out.File
	file_get_stock_info_jq_proto_rawDesc = nil
	file_get_stock_info_jq_proto_goTypes = nil
	file_get_stock_info_jq_proto_depIdxs = nil
}
