// data-analysis-python\src\get_stock_info_jq\get_stock_info_jq.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0--rc2
// source: get_stock_info_jq.proto

package get_stock_info_jq

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetStockInfoJqService_GetStockInfoJq_FullMethodName = "/GetStockInfoJqService/GetStockInfoJq"
)

// GetStockInfoJqServiceClient is the client API for GetStockInfoJqService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 株式ティッカー情報を取得するためのサービスを定義
type GetStockInfoJqServiceClient interface {
	GetStockInfoJq(ctx context.Context, in *GetStockInfoJqRequest, opts ...grpc.CallOption) (*GetStockInfoJqResponse, error)
}

type getStockInfoJqServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetStockInfoJqServiceClient(cc grpc.ClientConnInterface) GetStockInfoJqServiceClient {
	return &getStockInfoJqServiceClient{cc}
}

func (c *getStockInfoJqServiceClient) GetStockInfoJq(ctx context.Context, in *GetStockInfoJqRequest, opts ...grpc.CallOption) (*GetStockInfoJqResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStockInfoJqResponse)
	err := c.cc.Invoke(ctx, GetStockInfoJqService_GetStockInfoJq_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetStockInfoJqServiceServer is the server API for GetStockInfoJqService service.
// All implementations must embed UnimplementedGetStockInfoJqServiceServer
// for forward compatibility.
//
// 株式ティッカー情報を取得するためのサービスを定義
type GetStockInfoJqServiceServer interface {
	GetStockInfoJq(context.Context, *GetStockInfoJqRequest) (*GetStockInfoJqResponse, error)
	mustEmbedUnimplementedGetStockInfoJqServiceServer()
}

// UnimplementedGetStockInfoJqServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetStockInfoJqServiceServer struct{}

func (UnimplementedGetStockInfoJqServiceServer) GetStockInfoJq(context.Context, *GetStockInfoJqRequest) (*GetStockInfoJqResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStockInfoJq not implemented")
}
func (UnimplementedGetStockInfoJqServiceServer) mustEmbedUnimplementedGetStockInfoJqServiceServer() {}
func (UnimplementedGetStockInfoJqServiceServer) testEmbeddedByValue()                               {}

// UnsafeGetStockInfoJqServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetStockInfoJqServiceServer will
// result in compilation errors.
type UnsafeGetStockInfoJqServiceServer interface {
	mustEmbedUnimplementedGetStockInfoJqServiceServer()
}

func RegisterGetStockInfoJqServiceServer(s grpc.ServiceRegistrar, srv GetStockInfoJqServiceServer) {
	// If the following call pancis, it indicates UnimplementedGetStockInfoJqServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetStockInfoJqService_ServiceDesc, srv)
}

func _GetStockInfoJqService_GetStockInfoJq_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockInfoJqRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetStockInfoJqServiceServer).GetStockInfoJq(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetStockInfoJqService_GetStockInfoJq_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetStockInfoJqServiceServer).GetStockInfoJq(ctx, req.(*GetStockInfoJqRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetStockInfoJqService_ServiceDesc is the grpc.ServiceDesc for GetStockInfoJqService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetStockInfoJqService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GetStockInfoJqService",
	HandlerType: (*GetStockInfoJqServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStockInfoJq",
			Handler:    _GetStockInfoJqService_GetStockInfoJq_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "get_stock_info_jq.proto",
}
