# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: simple_moving_average.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'simple_moving_average.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bsimple_moving_average.proto\"S\n\tStockData\x12\x0c\n\x04open\x18\x01 \x01(\x01\x12\r\n\x05\x63lose\x18\x02 \x01(\x01\x12\x0c\n\x04high\x18\x03 \x01(\x01\x12\x0b\n\x03low\x18\x04 \x01(\x01\x12\x0e\n\x06volume\x18\x05 \x01(\x01\"\xbf\x01\n\x1aSimpleMovingAverageRequest\x12>\n\nstock_data\x18\x01 \x03(\x0b\x32*.SimpleMovingAverageRequest.StockDataEntry\x12\x0e\n\x06period\x18\x02 \x01(\x05\x12\x13\n\x0bwindow_size\x18\x03 \x01(\x05\x1a<\n\x0eStockDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.StockData:\x02\x38\x01\"\x9c\x01\n\x1bSimpleMovingAverageResponse\x12G\n\x0emoving_average\x18\x01 \x03(\x0b\x32/.SimpleMovingAverageResponse.MovingAverageEntry\x1a\x34\n\x12MovingAverageEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x32y\n\x1aSimpleMovingAverageService\x12[\n\x1c\x43\x61lculateSimpleMovingAverage\x12\x1b.SimpleMovingAverageRequest\x1a\x1c.SimpleMovingAverageResponse\"\x00\x42IZGapi-go/src/service/ms_gateway/calculate_indicator/simple_moving_averageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simple_moving_average_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZGapi-go/src/service/ms_gateway/calculate_indicator/simple_moving_average'
  _globals['_SIMPLEMOVINGAVERAGEREQUEST_STOCKDATAENTRY']._loaded_options = None
  _globals['_SIMPLEMOVINGAVERAGEREQUEST_STOCKDATAENTRY']._serialized_options = b'8\001'
  _globals['_SIMPLEMOVINGAVERAGERESPONSE_MOVINGAVERAGEENTRY']._loaded_options = None
  _globals['_SIMPLEMOVINGAVERAGERESPONSE_MOVINGAVERAGEENTRY']._serialized_options = b'8\001'
  _globals['_STOCKDATA']._serialized_start=31
  _globals['_STOCKDATA']._serialized_end=114
  _globals['_SIMPLEMOVINGAVERAGEREQUEST']._serialized_start=117
  _globals['_SIMPLEMOVINGAVERAGEREQUEST']._serialized_end=308
  _globals['_SIMPLEMOVINGAVERAGEREQUEST_STOCKDATAENTRY']._serialized_start=248
  _globals['_SIMPLEMOVINGAVERAGEREQUEST_STOCKDATAENTRY']._serialized_end=308
  _globals['_SIMPLEMOVINGAVERAGERESPONSE']._serialized_start=311
  _globals['_SIMPLEMOVINGAVERAGERESPONSE']._serialized_end=467
  _globals['_SIMPLEMOVINGAVERAGERESPONSE_MOVINGAVERAGEENTRY']._serialized_start=415
  _globals['_SIMPLEMOVINGAVERAGERESPONSE_MOVINGAVERAGEENTRY']._serialized_end=467
  _globals['_SIMPLEMOVINGAVERAGESERVICE']._serialized_start=469
  _globals['_SIMPLEMOVINGAVERAGESERVICE']._serialized_end=590
# @@protoc_insertion_point(module_scope)
