# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import simple_moving_average_pb2 as simple__moving__average__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in simple_moving_average_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimpleMovingAverageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateSimpleMovingAverage = channel.unary_unary(
                '/SimpleMovingAverageService/CalculateSimpleMovingAverage',
                request_serializer=simple__moving__average__pb2.SimpleMovingAverageRequest.SerializeToString,
                response_deserializer=simple__moving__average__pb2.SimpleMovingAverageResponse.FromString,
                _registered_method=True)


class SimpleMovingAverageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculateSimpleMovingAverage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimpleMovingAverageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateSimpleMovingAverage': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateSimpleMovingAverage,
                    request_deserializer=simple__moving__average__pb2.SimpleMovingAverageRequest.FromString,
                    response_serializer=simple__moving__average__pb2.SimpleMovingAverageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SimpleMovingAverageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SimpleMovingAverageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimpleMovingAverageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculateSimpleMovingAverage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SimpleMovingAverageService/CalculateSimpleMovingAverage',
            simple__moving__average__pb2.SimpleMovingAverageRequest.SerializeToString,
            simple__moving__average__pb2.SimpleMovingAverageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
