# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculate_indicator.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'calculate_indicator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63\x61lculate_indicator.proto\"7\n\x10IndicatorRequest\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x13\n\x0bwindow_size\x18\x02 \x01(\x05\"+\n\x11IndicatorResponse\x12\x16\n\x0emoving_average\x18\x01 \x03(\x01\x32U\n\x10IndicatorService\x12\x41\n\x16\x43\x61lculateMovingAverage\x12\x11.IndicatorRequest\x1a\x12.IndicatorResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculate_indicator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INDICATORREQUEST']._serialized_start=29
  _globals['_INDICATORREQUEST']._serialized_end=84
  _globals['_INDICATORRESPONSE']._serialized_start=86
  _globals['_INDICATORRESPONSE']._serialized_end=129
  _globals['_INDICATORSERVICE']._serialized_start=131
  _globals['_INDICATORSERVICE']._serialized_end=216
# @@protoc_insertion_point(module_scope)
