# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: get_all_tickers.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'get_all_tickers.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15get_all_tickers.proto\"\x16\n\x14GetAllTickersRequest\"(\n\x15GetAllTickersResponse\x12\x0f\n\x07tickers\x18\x01 \x03(\t2V\n\x14GetAllTickersService\x12>\n\rGetAllTickers\x12\x15.GetAllTickersRequest\x1a\x16.GetAllTickersResponseB/Z-api-go/src/service/ms_gateway/get_all_tickersb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_all_tickers_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z-api-go/src/service/ms_gateway/get_all_tickers'
  _globals['_GETALLTICKERSREQUEST']._serialized_start=25
  _globals['_GETALLTICKERSREQUEST']._serialized_end=47
  _globals['_GETALLTICKERSRESPONSE']._serialized_start=49
  _globals['_GETALLTICKERSRESPONSE']._serialized_end=89
  _globals['_GETALLTICKERSSERVICE']._serialized_start=91
  _globals['_GETALLTICKERSSERVICE']._serialized_end=177
# @@protoc_insertion_point(module_scope)
