# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import get_all_tickers_pb2 as get__all__tickers__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in get_all_tickers_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GetAllTickersServiceStub(object):
    """全世界の株式ティッカーを取得するためのサービスを定義
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllTickers = channel.unary_unary(
                '/GetAllTickersService/GetAllTickers',
                request_serializer=get__all__tickers__pb2.GetAllTickersRequest.SerializeToString,
                response_deserializer=get__all__tickers__pb2.GetAllTickersResponse.FromString,
                _registered_method=True)


class GetAllTickersServiceServicer(object):
    """全世界の株式ティッカーを取得するためのサービスを定義
    """

    def GetAllTickers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetAllTickersServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllTickers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllTickers,
                    request_deserializer=get__all__tickers__pb2.GetAllTickersRequest.FromString,
                    response_serializer=get__all__tickers__pb2.GetAllTickersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GetAllTickersService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('GetAllTickersService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GetAllTickersService(object):
    """全世界の株式ティッカーを取得するためのサービスを定義
    """

    @staticmethod
    def GetAllTickers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GetAllTickersService/GetAllTickers',
            get__all__tickers__pb2.GetAllTickersRequest.SerializeToString,
            get__all__tickers__pb2.GetAllTickersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
