// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.29.0--rc2
// source: simple_moving_average.proto

package simple_moving_average

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimpleMovingAverageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StockData  []float32 `protobuf:"fixed32,1,rep,packed,name=stock_data,json=stockData,proto3" json:"stock_data,omitempty"`
	WindowSize int32     `protobuf:"varint,2,opt,name=window_size,json=windowSize,proto3" json:"window_size,omitempty"`
}

func (x *SimpleMovingAverageRequest) Reset() {
	*x = SimpleMovingAverageRequest{}
	mi := &file_simple_moving_average_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleMovingAverageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleMovingAverageRequest) ProtoMessage() {}

func (x *SimpleMovingAverageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simple_moving_average_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleMovingAverageRequest.ProtoReflect.Descriptor instead.
func (*SimpleMovingAverageRequest) Descriptor() ([]byte, []int) {
	return file_simple_moving_average_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleMovingAverageRequest) GetStockData() []float32 {
	if x != nil {
		return x.StockData
	}
	return nil
}

func (x *SimpleMovingAverageRequest) GetWindowSize() int32 {
	if x != nil {
		return x.WindowSize
	}
	return 0
}

type SimpleMovingAverageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []float64 `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *SimpleMovingAverageResponse) Reset() {
	*x = SimpleMovingAverageResponse{}
	mi := &file_simple_moving_average_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleMovingAverageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleMovingAverageResponse) ProtoMessage() {}

func (x *SimpleMovingAverageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simple_moving_average_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleMovingAverageResponse.ProtoReflect.Descriptor instead.
func (*SimpleMovingAverageResponse) Descriptor() ([]byte, []int) {
	return file_simple_moving_average_proto_rawDescGZIP(), []int{1}
}

func (x *SimpleMovingAverageResponse) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_simple_moving_average_proto protoreflect.FileDescriptor

var file_simple_moving_average_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x6d, 0x6f, 0x76, 0x69, 0x6e, 0x67, 0x5f,
	0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5c, 0x0a,
	0x1a, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x6e, 0x67, 0x41, 0x76, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52,
	0x09, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x69,
	0x6e, 0x64, 0x6f, 0x77, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x35, 0x0a, 0x1b, 0x53,
	0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x6e, 0x67, 0x41, 0x76, 0x65, 0x72, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x32, 0x79, 0x0a, 0x1a, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x6f, 0x76, 0x69,
	0x6e, 0x67, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x5b, 0x0a, 0x1c, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x69, 0x6d,
	0x70, 0x6c, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x6e, 0x67, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65,
	0x12, 0x1b, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x6e, 0x67, 0x41,
	0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x6e, 0x67, 0x41, 0x76, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x32, 0x5a,
	0x30, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x73, 0x69, 0x6d, 0x70,
	0x6c, 0x65, 0x5f, 0x6d, 0x6f, 0x76, 0x69, 0x6e, 0x67, 0x5f, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_simple_moving_average_proto_rawDescOnce sync.Once
	file_simple_moving_average_proto_rawDescData = file_simple_moving_average_proto_rawDesc
)

func file_simple_moving_average_proto_rawDescGZIP() []byte {
	file_simple_moving_average_proto_rawDescOnce.Do(func() {
		file_simple_moving_average_proto_rawDescData = protoimpl.X.CompressGZIP(file_simple_moving_average_proto_rawDescData)
	})
	return file_simple_moving_average_proto_rawDescData
}

var file_simple_moving_average_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_simple_moving_average_proto_goTypes = []any{
	(*SimpleMovingAverageRequest)(nil),  // 0: SimpleMovingAverageRequest
	(*SimpleMovingAverageResponse)(nil), // 1: SimpleMovingAverageResponse
}
var file_simple_moving_average_proto_depIdxs = []int32{
	0, // 0: SimpleMovingAverageService.CalculateSimpleMovingAverage:input_type -> SimpleMovingAverageRequest
	1, // 1: SimpleMovingAverageService.CalculateSimpleMovingAverage:output_type -> SimpleMovingAverageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_simple_moving_average_proto_init() }
func file_simple_moving_average_proto_init() {
	if File_simple_moving_average_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_simple_moving_average_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_simple_moving_average_proto_goTypes,
		DependencyIndexes: file_simple_moving_average_proto_depIdxs,
		MessageInfos:      file_simple_moving_average_proto_msgTypes,
	}.Build()
	File_simple_moving_average_proto = out.File
	file_simple_moving_average_proto_rawDesc = nil
	file_simple_moving_average_proto_goTypes = nil
	file_simple_moving_average_proto_depIdxs = nil
}
