# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: get_stock_data_with_dates.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'get_stock_data_with_dates.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fget_stock_data_with_dates.proto\"T\n\x1cGetStockDataWithDatesRequest\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x03 \x01(\t\"\\\n\x12StockDataWithDates\x12\x0c\n\x04open\x18\x01 \x01(\x01\x12\r\n\x05\x63lose\x18\x02 \x01(\x01\x12\x0c\n\x04high\x18\x03 \x01(\x01\x12\x0b\n\x03low\x18\x04 \x01(\x01\x12\x0e\n\x06volume\x18\x05 \x01(\x01\"\xbd\x01\n\x1dGetStockDataWithDatesResponse\x12\x41\n\nstock_data\x18\x01 \x03(\x0b\x32-.GetStockDataWithDatesResponse.StockDataEntry\x12\x12\n\nstock_name\x18\x02 \x01(\t\x1a\x45\n\x0eStockDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.StockDataWithDates:\x02\x38\x01\x32m\n\x1cGetStockDataWithDatesService\x12M\n\x0cGetStockData\x12\x1d.GetStockDataWithDatesRequest\x1a\x1e.GetStockDataWithDatesResponseB9Z7api-go/src/service/ms_gateway/get_stock_data_with_datesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_stock_data_with_dates_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7api-go/src/service/ms_gateway/get_stock_data_with_dates'
  _globals['_GETSTOCKDATAWITHDATESRESPONSE_STOCKDATAENTRY']._loaded_options = None
  _globals['_GETSTOCKDATAWITHDATESRESPONSE_STOCKDATAENTRY']._serialized_options = b'8\001'
  _globals['_GETSTOCKDATAWITHDATESREQUEST']._serialized_start=35
  _globals['_GETSTOCKDATAWITHDATESREQUEST']._serialized_end=119
  _globals['_STOCKDATAWITHDATES']._serialized_start=121
  _globals['_STOCKDATAWITHDATES']._serialized_end=213
  _globals['_GETSTOCKDATAWITHDATESRESPONSE']._serialized_start=216
  _globals['_GETSTOCKDATAWITHDATESRESPONSE']._serialized_end=405
  _globals['_GETSTOCKDATAWITHDATESRESPONSE_STOCKDATAENTRY']._serialized_start=336
  _globals['_GETSTOCKDATAWITHDATESRESPONSE_STOCKDATAENTRY']._serialized_end=405
  _globals['_GETSTOCKDATAWITHDATESSERVICE']._serialized_start=407
  _globals['_GETSTOCKDATAWITHDATESSERVICE']._serialized_end=516
# @@protoc_insertion_point(module_scope)
