# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: get_us_stock_info.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'get_us_stock_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17get_us_stock_info.proto\"\x17\n\x15GetUsStockInfoRequest\"\xa7\x01\n\tStockInfo\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\tfull_name\x18\x04 \x01(\t\x12\x0c\n\x04isin\x18\x05 \x01(\t\x12\x10\n\x08\x63urrency\x18\x06 \x01(\t\x12\x16\n\x0estock_exchange\x18\x07 \x01(\t\x12\x0e\n\x06sector\x18\x08 \x01(\t\x12\x10\n\x08industry\x18\t \x01(\t\"4\n\x16GetUsStockInfoResponse\x12\x1a\n\x06stocks\x18\x01 \x03(\x0b\x32\n.StockInfo2Z\n\x15GetUsStockInfoService\x12\x41\n\x0eGetUsStockInfo\x12\x16.GetUsStockInfoRequest\x1a\x17.GetUsStockInfoResponseB1Z/api-go/src/service/ms_gateway/get_us_stock_infob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_us_stock_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/api-go/src/service/ms_gateway/get_us_stock_info'
  _globals['_GETUSSTOCKINFOREQUEST']._serialized_start=27
  _globals['_GETUSSTOCKINFOREQUEST']._serialized_end=50
  _globals['_STOCKINFO']._serialized_start=53
  _globals['_STOCKINFO']._serialized_end=220
  _globals['_GETUSSTOCKINFORESPONSE']._serialized_start=222
  _globals['_GETUSSTOCKINFORESPONSE']._serialized_end=274
  _globals['_GETUSSTOCKINFOSERVICE']._serialized_start=276
  _globals['_GETUSSTOCKINFOSERVICE']._serialized_end=366
# @@protoc_insertion_point(module_scope)
