// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.29.0--rc2
// source: generate_chart.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StockData     []float32 `protobuf:"fixed32,1,rep,packed,name=stock_data,json=stockData,proto3" json:"stock_data,omitempty"`             // 株価データ
	IndicatorData []float32 `protobuf:"fixed32,2,rep,packed,name=indicator_data,json=indicatorData,proto3" json:"indicator_data,omitempty"` // 指標データ
	Ticker        string    `protobuf:"bytes,3,opt,name=ticker,proto3" json:"ticker,omitempty"`                                             // ティッカーシンボル
}

func (x *ChartRequest) Reset() {
	*x = ChartRequest{}
	mi := &file_generate_chart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartRequest) ProtoMessage() {}

func (x *ChartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_generate_chart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartRequest.ProtoReflect.Descriptor instead.
func (*ChartRequest) Descriptor() ([]byte, []int) {
	return file_generate_chart_proto_rawDescGZIP(), []int{0}
}

func (x *ChartRequest) GetStockData() []float32 {
	if x != nil {
		return x.StockData
	}
	return nil
}

func (x *ChartRequest) GetIndicatorData() []float32 {
	if x != nil {
		return x.IndicatorData
	}
	return nil
}

func (x *ChartRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

type ChartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChartData string `protobuf:"bytes,1,opt,name=chart_data,json=chartData,proto3" json:"chart_data,omitempty"` // Base64エンコードされた画像データ
}

func (x *ChartResponse) Reset() {
	*x = ChartResponse{}
	mi := &file_generate_chart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartResponse) ProtoMessage() {}

func (x *ChartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_generate_chart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartResponse.ProtoReflect.Descriptor instead.
func (*ChartResponse) Descriptor() ([]byte, []int) {
	return file_generate_chart_proto_rawDescGZIP(), []int{1}
}

func (x *ChartResponse) GetChartData() string {
	if x != nil {
		return x.ChartData
	}
	return ""
}

var File_generate_chart_proto protoreflect.FileDescriptor

var file_generate_chart_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x63,
	0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74,
	0x6f, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x02, 0x52, 0x0d, 0x69,
	0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x69,
	0x63, 0x6b, 0x65, 0x72, 0x22, 0x2e, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x72, 0x74, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x72, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x32, 0x40, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x72, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x0d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x43, 0x68, 0x61, 0x72, 0x74, 0x12, 0x0d, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1c, 0x5a, 0x1a, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x6f,
	0x2f, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_generate_chart_proto_rawDescOnce sync.Once
	file_generate_chart_proto_rawDescData = file_generate_chart_proto_rawDesc
)

func file_generate_chart_proto_rawDescGZIP() []byte {
	file_generate_chart_proto_rawDescOnce.Do(func() {
		file_generate_chart_proto_rawDescData = protoimpl.X.CompressGZIP(file_generate_chart_proto_rawDescData)
	})
	return file_generate_chart_proto_rawDescData
}

var file_generate_chart_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_generate_chart_proto_goTypes = []any{
	(*ChartRequest)(nil),  // 0: ChartRequest
	(*ChartResponse)(nil), // 1: ChartResponse
}
var file_generate_chart_proto_depIdxs = []int32{
	0, // 0: ChartService.GenerateChart:input_type -> ChartRequest
	1, // 1: ChartService.GenerateChart:output_type -> ChartResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_generate_chart_proto_init() }
func file_generate_chart_proto_init() {
	if File_generate_chart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_generate_chart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_generate_chart_proto_goTypes,
		DependencyIndexes: file_generate_chart_proto_depIdxs,
		MessageInfos:      file_generate_chart_proto_msgTypes,
	}.Build()
	File_generate_chart_proto = out.File
	file_generate_chart_proto_rawDesc = nil
	file_generate_chart_proto_goTypes = nil
	file_generate_chart_proto_depIdxs = nil
}
