// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0--rc2
// source: get_stock.proto

package gateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetStockService_GetStockData_FullMethodName = "/GetStockService/GetStockData"
)

// GetStockServiceClient is the client API for GetStockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GetStockServiceというサービスを定義
type GetStockServiceClient interface {
	// GetStockDataというRPCメソッドを定義
	GetStockData(ctx context.Context, in *GetStockRequest, opts ...grpc.CallOption) (*GetStockResponse, error)
}

type getStockServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetStockServiceClient(cc grpc.ClientConnInterface) GetStockServiceClient {
	return &getStockServiceClient{cc}
}

func (c *getStockServiceClient) GetStockData(ctx context.Context, in *GetStockRequest, opts ...grpc.CallOption) (*GetStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStockResponse)
	err := c.cc.Invoke(ctx, GetStockService_GetStockData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetStockServiceServer is the server API for GetStockService service.
// All implementations must embed UnimplementedGetStockServiceServer
// for forward compatibility.
//
// GetStockServiceというサービスを定義
type GetStockServiceServer interface {
	// GetStockDataというRPCメソッドを定義
	GetStockData(context.Context, *GetStockRequest) (*GetStockResponse, error)
	mustEmbedUnimplementedGetStockServiceServer()
}

// UnimplementedGetStockServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetStockServiceServer struct{}

func (UnimplementedGetStockServiceServer) GetStockData(context.Context, *GetStockRequest) (*GetStockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStockData not implemented")
}
func (UnimplementedGetStockServiceServer) mustEmbedUnimplementedGetStockServiceServer() {}
func (UnimplementedGetStockServiceServer) testEmbeddedByValue()                         {}

// UnsafeGetStockServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetStockServiceServer will
// result in compilation errors.
type UnsafeGetStockServiceServer interface {
	mustEmbedUnimplementedGetStockServiceServer()
}

func RegisterGetStockServiceServer(s grpc.ServiceRegistrar, srv GetStockServiceServer) {
	// If the following call pancis, it indicates UnimplementedGetStockServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetStockService_ServiceDesc, srv)
}

func _GetStockService_GetStockData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetStockServiceServer).GetStockData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetStockService_GetStockData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetStockServiceServer).GetStockData(ctx, req.(*GetStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetStockService_ServiceDesc is the grpc.ServiceDesc for GetStockService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetStockService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GetStockService",
	HandlerType: (*GetStockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStockData",
			Handler:    _GetStockService_GetStockData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "get_stock.proto",
}
