# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import get_trading_calendar_jq_pb2 as get__trading__calendar__jq__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in get_trading_calendar_jq_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GetTradingCalendarJqServiceStub(object):
    """GetTradingCalendarJqServiceというサービスを定義
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTradingCalendarJq = channel.unary_unary(
                '/GetTradingCalendarJqService/GetTradingCalendarJq',
                request_serializer=get__trading__calendar__jq__pb2.GetTradingCalendarJqRequest.SerializeToString,
                response_deserializer=get__trading__calendar__jq__pb2.GetTradingCalendarJqResponse.FromString,
                _registered_method=True)


class GetTradingCalendarJqServiceServicer(object):
    """GetTradingCalendarJqServiceというサービスを定義
    """

    def GetTradingCalendarJq(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetTradingCalendarJqServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTradingCalendarJq': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTradingCalendarJq,
                    request_deserializer=get__trading__calendar__jq__pb2.GetTradingCalendarJqRequest.FromString,
                    response_serializer=get__trading__calendar__jq__pb2.GetTradingCalendarJqResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GetTradingCalendarJqService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('GetTradingCalendarJqService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GetTradingCalendarJqService(object):
    """GetTradingCalendarJqServiceというサービスを定義
    """

    @staticmethod
    def GetTradingCalendarJq(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GetTradingCalendarJqService/GetTradingCalendarJq',
            get__trading__calendar__jq__pb2.GetTradingCalendarJqRequest.SerializeToString,
            get__trading__calendar__jq__pb2.GetTradingCalendarJqResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
